global consumer_key,consumer_secret,access_token_key,access_token_secret
consumer_key='bYa4JD9WSamEVABRbxHaUzTHJ'
consumer_secret='byGpIOUTbMuikrOT7DGaJWbHzWK4PO9IyQc4wo4s2I3tMJnZeE'
access_token_key='4844792894-p6HZrNoGcFhJnr5aHOwNnpj8XOM2yiKKReYmO8J'
access_token_secret='9nk4Z6bee0IR9dqOr9Pf0gXTRhYdtzrOMt0zdwZdLIOld'